// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jamo/v1/event.proto

package jamov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_jamo_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEventsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_jamo_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_jamo_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_jamo_v1_event_proto protoreflect.FileDescriptor

const file_jamo_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x13jamo/v1/event.proto\x12\ajamo.v1\"8\n" +
	"\x13StreamEventsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"h\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs2N\n" +
	"\fEventService\x12>\n" +
	"\fStreamEvents\x12\x1c.jamo.v1.StreamEventsRequest\x1a\x0e.jamo.v1.Event0\x01B8Z6github.com/jamojamo/studio/engine/proto/jamo/v1;jamov1b\x06proto3"

var (
	file_jamo_v1_event_proto_rawDescOnce sync.Once
	file_jamo_v1_event_proto_rawDescData []byte
)

func file_jamo_v1_event_proto_rawDescGZIP() []byte {
	file_jamo_v1_event_proto_rawDescOnce.Do(func() {
		file_jamo_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jamo_v1_event_proto_rawDesc), len(file_jamo_v1_event_proto_rawDesc)))
	})
	return file_jamo_v1_event_proto_rawDescData
}

var file_jamo_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jamo_v1_event_proto_goTypes = []any{
	(*StreamEventsRequest)(nil), // 0: jamo.v1.StreamEventsRequest
	(*Event)(nil),               // 1: jamo.v1.Event
}
var file_jamo_v1_event_proto_depIdxs = []int32{
	0, // 0: jamo.v1.EventService.StreamEvents:input_type -> jamo.v1.StreamEventsRequest
	1, // 1: jamo.v1.EventService.StreamEvents:output_type -> jamo.v1.Event
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jamo_v1_event_proto_init() }
func file_jamo_v1_event_proto_init() {
	if File_jamo_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jamo_v1_event_proto_rawDesc), len(file_jamo_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jamo_v1_event_proto_goTypes,
		DependencyIndexes: file_jamo_v1_event_proto_depIdxs,
		MessageInfos:      file_jamo_v1_event_proto_msgTypes,
	}.Build()
	File_jamo_v1_event_proto = out.File
	file_jamo_v1_event_proto_goTypes = nil
	file_jamo_v1_event_proto_depIdxs = nil
}
