// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jamo/v1/generate.proto

package jamov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_jamo_v1_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_generate_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type Patch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patch) Reset() {
	*x = Patch{}
	mi := &file_jamo_v1_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patch) ProtoMessage() {}

func (x *Patch) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patch.ProtoReflect.Descriptor instead.
func (*Patch) Descriptor() ([]byte, []int) {
	return file_jamo_v1_generate_proto_rawDescGZIP(), []int{1}
}

func (x *Patch) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Patch) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Patches       []*Patch               `protobuf:"bytes,2,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_jamo_v1_generate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_generate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_generate_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GenerateResponse) GetPatches() []*Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type ApplyPatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Patches       []*Patch               `protobuf:"bytes,3,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPatchesRequest) Reset() {
	*x = ApplyPatchesRequest{}
	mi := &file_jamo_v1_generate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPatchesRequest) ProtoMessage() {}

func (x *ApplyPatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_generate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPatchesRequest.ProtoReflect.Descriptor instead.
func (*ApplyPatchesRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_generate_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyPatchesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ApplyPatchesRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ApplyPatchesRequest) GetPatches() []*Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type PatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Applied       bool                   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchResult) Reset() {
	*x = PatchResult{}
	mi := &file_jamo_v1_generate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchResult) ProtoMessage() {}

func (x *PatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_generate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchResult.ProtoReflect.Descriptor instead.
func (*PatchResult) Descriptor() ([]byte, []int) {
	return file_jamo_v1_generate_proto_rawDescGZIP(), []int{4}
}

func (x *PatchResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *PatchResult) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *PatchResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ApplyPatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PatchResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPatchesResponse) Reset() {
	*x = ApplyPatchesResponse{}
	mi := &file_jamo_v1_generate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPatchesResponse) ProtoMessage() {}

func (x *ApplyPatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_generate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPatchesResponse.ProtoReflect.Descriptor instead.
func (*ApplyPatchesResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_generate_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyPatchesResponse) GetResults() []*PatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_jamo_v1_generate_proto protoreflect.FileDescriptor

const file_jamo_v1_generate_proto_rawDesc = "" +
	"\n" +
	"\x16jamo/v1/generate.proto\x12\ajamo.v1\"L\n" +
	"\x0fGenerateRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\">\n" +
	"\x05Patch\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"U\n" +
	"\x10GenerateResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\apatches\x18\x02 \x03(\v2\x0e.jamo.v1.PatchR\apatches\"{\n" +
	"\x13ApplyPatchesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12(\n" +
	"\apatches\x18\x03 \x03(\v2\x0e.jamo.v1.PatchR\apatches\"Z\n" +
	"\vPatchResult\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\aapplied\x18\x02 \x01(\bR\aapplied\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x14ApplyPatchesResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.jamo.v1.PatchResultR\aresults2\x9f\x01\n" +
	"\x0fGenerateService\x12?\n" +
	"\bGenerate\x12\x18.jamo.v1.GenerateRequest\x1a\x19.jamo.v1.GenerateResponse\x12K\n" +
	"\fApplyPatches\x12\x1c.jamo.v1.ApplyPatchesRequest\x1a\x1d.jamo.v1.ApplyPatchesResponseB8Z6github.com/jamojamo/studio/engine/proto/jamo/v1;jamov1b\x06proto3"

var (
	file_jamo_v1_generate_proto_rawDescOnce sync.Once
	file_jamo_v1_generate_proto_rawDescData []byte
)

func file_jamo_v1_generate_proto_rawDescGZIP() []byte {
	file_jamo_v1_generate_proto_rawDescOnce.Do(func() {
		file_jamo_v1_generate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jamo_v1_generate_proto_rawDesc), len(file_jamo_v1_generate_proto_rawDesc)))
	})
	return file_jamo_v1_generate_proto_rawDescData
}

var file_jamo_v1_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jamo_v1_generate_proto_goTypes = []any{
	(*GenerateRequest)(nil),      // 0: jamo.v1.GenerateRequest
	(*Patch)(nil),                // 1: jamo.v1.Patch
	(*GenerateResponse)(nil),     // 2: jamo.v1.GenerateResponse
	(*ApplyPatchesRequest)(nil),  // 3: jamo.v1.ApplyPatchesRequest
	(*PatchResult)(nil),          // 4: jamo.v1.PatchResult
	(*ApplyPatchesResponse)(nil), // 5: jamo.v1.ApplyPatchesResponse
}
var file_jamo_v1_generate_proto_depIdxs = []int32{
	1, // 0: jamo.v1.GenerateResponse.patches:type_name -> jamo.v1.Patch
	1, // 1: jamo.v1.ApplyPatchesRequest.patches:type_name -> jamo.v1.Patch
	4, // 2: jamo.v1.ApplyPatchesResponse.results:type_name -> jamo.v1.PatchResult
	0, // 3: jamo.v1.GenerateService.Generate:input_type -> jamo.v1.GenerateRequest
	3, // 4: jamo.v1.GenerateService.ApplyPatches:input_type -> jamo.v1.ApplyPatchesRequest
	2, // 5: jamo.v1.GenerateService.Generate:output_type -> jamo.v1.GenerateResponse
	5, // 6: jamo.v1.GenerateService.ApplyPatches:output_type -> jamo.v1.ApplyPatchesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_jamo_v1_generate_proto_init() }
func file_jamo_v1_generate_proto_init() {
	if File_jamo_v1_generate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jamo_v1_generate_proto_rawDesc), len(file_jamo_v1_generate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jamo_v1_generate_proto_goTypes,
		DependencyIndexes: file_jamo_v1_generate_proto_depIdxs,
		MessageInfos:      file_jamo_v1_generate_proto_msgTypes,
	}.Build()
	File_jamo_v1_generate_proto = out.File
	file_jamo_v1_generate_proto_goTypes = nil
	file_jamo_v1_generate_proto_depIdxs = nil
}
