// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jamo/v1/git.proto

package jamov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitInitRequest) Reset() {
	*x = GitInitRequest{}
	mi := &file_jamo_v1_git_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitInitRequest) ProtoMessage() {}

func (x *GitInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitInitRequest.ProtoReflect.Descriptor instead.
func (*GitInitRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{0}
}

func (x *GitInitRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type GitInitResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AlreadyInitialized bool                   `protobuf:"varint,1,opt,name=already_initialized,json=alreadyInitialized,proto3" json:"already_initialized,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GitInitResponse) Reset() {
	*x = GitInitResponse{}
	mi := &file_jamo_v1_git_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitInitResponse) ProtoMessage() {}

func (x *GitInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitInitResponse.ProtoReflect.Descriptor instead.
func (*GitInitResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{1}
}

func (x *GitInitResponse) GetAlreadyInitialized() bool {
	if x != nil {
		return x.AlreadyInitialized
	}
	return false
}

type GitStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitStatusRequest) Reset() {
	*x = GitStatusRequest{}
	mi := &file_jamo_v1_git_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitStatusRequest) ProtoMessage() {}

func (x *GitStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitStatusRequest.ProtoReflect.Descriptor instead.
func (*GitStatusRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{2}
}

func (x *GitStatusRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type GitStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*ChangedFile         `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	IsClean       bool                   `protobuf:"varint,2,opt,name=is_clean,json=isClean,proto3" json:"is_clean,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitStatusResponse) Reset() {
	*x = GitStatusResponse{}
	mi := &file_jamo_v1_git_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitStatusResponse) ProtoMessage() {}

func (x *GitStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitStatusResponse.ProtoReflect.Descriptor instead.
func (*GitStatusResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{3}
}

func (x *GitStatusResponse) GetFiles() []*ChangedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GitStatusResponse) GetIsClean() bool {
	if x != nil {
		return x.IsClean
	}
	return false
}

type ChangedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedFile) Reset() {
	*x = ChangedFile{}
	mi := &file_jamo_v1_git_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedFile) ProtoMessage() {}

func (x *ChangedFile) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedFile.ProtoReflect.Descriptor instead.
func (*ChangedFile) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{4}
}

func (x *ChangedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChangedFile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GitDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiffRequest) Reset() {
	*x = GitDiffRequest{}
	mi := &file_jamo_v1_git_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiffRequest) ProtoMessage() {}

func (x *GitDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiffRequest.ProtoReflect.Descriptor instead.
func (*GitDiffRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{5}
}

func (x *GitDiffRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GitDiffRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type GitDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiffResponse) Reset() {
	*x = GitDiffResponse{}
	mi := &file_jamo_v1_git_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiffResponse) ProtoMessage() {}

func (x *GitDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiffResponse.ProtoReflect.Descriptor instead.
func (*GitDiffResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{6}
}

func (x *GitDiffResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

type GitCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCommitRequest) Reset() {
	*x = GitCommitRequest{}
	mi := &file_jamo_v1_git_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCommitRequest) ProtoMessage() {}

func (x *GitCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCommitRequest.ProtoReflect.Descriptor instead.
func (*GitCommitRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{7}
}

func (x *GitCommitRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GitCommitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GitCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCommitResponse) Reset() {
	*x = GitCommitResponse{}
	mi := &file_jamo_v1_git_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCommitResponse) ProtoMessage() {}

func (x *GitCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCommitResponse.ProtoReflect.Descriptor instead.
func (*GitCommitResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{8}
}

func (x *GitCommitResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type GitLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLogRequest) Reset() {
	*x = GitLogRequest{}
	mi := &file_jamo_v1_git_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLogRequest) ProtoMessage() {}

func (x *GitLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLogRequest.ProtoReflect.Descriptor instead.
func (*GitLogRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{9}
}

func (x *GitLogRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GitLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GitLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*GitLogEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLogResponse) Reset() {
	*x = GitLogResponse{}
	mi := &file_jamo_v1_git_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLogResponse) ProtoMessage() {}

func (x *GitLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLogResponse.ProtoReflect.Descriptor instead.
func (*GitLogResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{10}
}

func (x *GitLogResponse) GetEntries() []*GitLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GitLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ShortHash     string                 `protobuf:"bytes,2,opt,name=short_hash,json=shortHash,proto3" json:"short_hash,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitLogEntry) Reset() {
	*x = GitLogEntry{}
	mi := &file_jamo_v1_git_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitLogEntry) ProtoMessage() {}

func (x *GitLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitLogEntry.ProtoReflect.Descriptor instead.
func (*GitLogEntry) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{11}
}

func (x *GitLogEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GitLogEntry) GetShortHash() string {
	if x != nil {
		return x.ShortHash
	}
	return ""
}

func (x *GitLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GitLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GitCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCheckoutRequest) Reset() {
	*x = GitCheckoutRequest{}
	mi := &file_jamo_v1_git_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCheckoutRequest) ProtoMessage() {}

func (x *GitCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCheckoutRequest.ProtoReflect.Descriptor instead.
func (*GitCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{12}
}

func (x *GitCheckoutRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GitCheckoutRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type GitCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitCheckoutResponse) Reset() {
	*x = GitCheckoutResponse{}
	mi := &file_jamo_v1_git_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitCheckoutResponse) ProtoMessage() {}

func (x *GitCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_git_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitCheckoutResponse.ProtoReflect.Descriptor instead.
func (*GitCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_git_proto_rawDescGZIP(), []int{13}
}

var File_jamo_v1_git_proto protoreflect.FileDescriptor

const file_jamo_v1_git_proto_rawDesc = "" +
	"\n" +
	"\x11jamo/v1/git.proto\x12\ajamo.v1\"3\n" +
	"\x0eGitInitRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"B\n" +
	"\x0fGitInitResponse\x12/\n" +
	"\x13already_initialized\x18\x01 \x01(\bR\x12alreadyInitialized\"5\n" +
	"\x10GitStatusRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"Z\n" +
	"\x11GitStatusResponse\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.jamo.v1.ChangedFileR\x05files\x12\x19\n" +
	"\bis_clean\x18\x02 \x01(\bR\aisClean\"9\n" +
	"\vChangedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"P\n" +
	"\x0eGitDiffRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\"%\n" +
	"\x0fGitDiffResponse\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\"O\n" +
	"\x10GitCommitRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x11GitCommitResponse\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\"H\n" +
	"\rGitLogRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"@\n" +
	"\x0eGitLogResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.jamo.v1.GitLogEntryR\aentries\"x\n" +
	"\vGitLogEntry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"short_hash\x18\x02 \x01(\tR\tshortHash\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"M\n" +
	"\x12GitCheckoutRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"\x15\n" +
	"\x13GitCheckoutResponse2\x83\x03\n" +
	"\n" +
	"GitService\x129\n" +
	"\x04Init\x12\x17.jamo.v1.GitInitRequest\x1a\x18.jamo.v1.GitInitResponse\x12?\n" +
	"\x06Status\x12\x19.jamo.v1.GitStatusRequest\x1a\x1a.jamo.v1.GitStatusResponse\x129\n" +
	"\x04Diff\x12\x17.jamo.v1.GitDiffRequest\x1a\x18.jamo.v1.GitDiffResponse\x12?\n" +
	"\x06Commit\x12\x19.jamo.v1.GitCommitRequest\x1a\x1a.jamo.v1.GitCommitResponse\x126\n" +
	"\x03Log\x12\x16.jamo.v1.GitLogRequest\x1a\x17.jamo.v1.GitLogResponse\x12E\n" +
	"\bCheckout\x12\x1b.jamo.v1.GitCheckoutRequest\x1a\x1c.jamo.v1.GitCheckoutResponseB8Z6github.com/jamojamo/studio/engine/proto/jamo/v1;jamov1b\x06proto3"

var (
	file_jamo_v1_git_proto_rawDescOnce sync.Once
	file_jamo_v1_git_proto_rawDescData []byte
)

func file_jamo_v1_git_proto_rawDescGZIP() []byte {
	file_jamo_v1_git_proto_rawDescOnce.Do(func() {
		file_jamo_v1_git_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jamo_v1_git_proto_rawDesc), len(file_jamo_v1_git_proto_rawDesc)))
	})
	return file_jamo_v1_git_proto_rawDescData
}

var file_jamo_v1_git_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_jamo_v1_git_proto_goTypes = []any{
	(*GitInitRequest)(nil),      // 0: jamo.v1.GitInitRequest
	(*GitInitResponse)(nil),     // 1: jamo.v1.GitInitResponse
	(*GitStatusRequest)(nil),    // 2: jamo.v1.GitStatusRequest
	(*GitStatusResponse)(nil),   // 3: jamo.v1.GitStatusResponse
	(*ChangedFile)(nil),         // 4: jamo.v1.ChangedFile
	(*GitDiffRequest)(nil),      // 5: jamo.v1.GitDiffRequest
	(*GitDiffResponse)(nil),     // 6: jamo.v1.GitDiffResponse
	(*GitCommitRequest)(nil),    // 7: jamo.v1.GitCommitRequest
	(*GitCommitResponse)(nil),   // 8: jamo.v1.GitCommitResponse
	(*GitLogRequest)(nil),       // 9: jamo.v1.GitLogRequest
	(*GitLogResponse)(nil),      // 10: jamo.v1.GitLogResponse
	(*GitLogEntry)(nil),         // 11: jamo.v1.GitLogEntry
	(*GitCheckoutRequest)(nil),  // 12: jamo.v1.GitCheckoutRequest
	(*GitCheckoutResponse)(nil), // 13: jamo.v1.GitCheckoutResponse
}
var file_jamo_v1_git_proto_depIdxs = []int32{
	4,  // 0: jamo.v1.GitStatusResponse.files:type_name -> jamo.v1.ChangedFile
	11, // 1: jamo.v1.GitLogResponse.entries:type_name -> jamo.v1.GitLogEntry
	0,  // 2: jamo.v1.GitService.Init:input_type -> jamo.v1.GitInitRequest
	2,  // 3: jamo.v1.GitService.Status:input_type -> jamo.v1.GitStatusRequest
	5,  // 4: jamo.v1.GitService.Diff:input_type -> jamo.v1.GitDiffRequest
	7,  // 5: jamo.v1.GitService.Commit:input_type -> jamo.v1.GitCommitRequest
	9,  // 6: jamo.v1.GitService.Log:input_type -> jamo.v1.GitLogRequest
	12, // 7: jamo.v1.GitService.Checkout:input_type -> jamo.v1.GitCheckoutRequest
	1,  // 8: jamo.v1.GitService.Init:output_type -> jamo.v1.GitInitResponse
	3,  // 9: jamo.v1.GitService.Status:output_type -> jamo.v1.GitStatusResponse
	6,  // 10: jamo.v1.GitService.Diff:output_type -> jamo.v1.GitDiffResponse
	8,  // 11: jamo.v1.GitService.Commit:output_type -> jamo.v1.GitCommitResponse
	10, // 12: jamo.v1.GitService.Log:output_type -> jamo.v1.GitLogResponse
	13, // 13: jamo.v1.GitService.Checkout:output_type -> jamo.v1.GitCheckoutResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_jamo_v1_git_proto_init() }
func file_jamo_v1_git_proto_init() {
	if File_jamo_v1_git_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jamo_v1_git_proto_rawDesc), len(file_jamo_v1_git_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jamo_v1_git_proto_goTypes,
		DependencyIndexes: file_jamo_v1_git_proto_depIdxs,
		MessageInfos:      file_jamo_v1_git_proto_msgTypes,
	}.Build()
	File_jamo_v1_git_proto = out.File
	file_jamo_v1_git_proto_goTypes = nil
	file_jamo_v1_git_proto_depIdxs = nil
}
