// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jamo/v1/health.proto

package jamov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_jamo_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_health_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_jamo_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_jamo_v1_health_proto protoreflect.FileDescriptor

const file_jamo_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x14jamo/v1/health.proto\x12\ajamo.v1\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2D\n" +
	"\rHealthService\x123\n" +
	"\x04Ping\x12\x14.jamo.v1.PingRequest\x1a\x15.jamo.v1.PingResponseB8Z6github.com/jamojamo/studio/engine/proto/jamo/v1;jamov1b\x06proto3"

var (
	file_jamo_v1_health_proto_rawDescOnce sync.Once
	file_jamo_v1_health_proto_rawDescData []byte
)

func file_jamo_v1_health_proto_rawDescGZIP() []byte {
	file_jamo_v1_health_proto_rawDescOnce.Do(func() {
		file_jamo_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jamo_v1_health_proto_rawDesc), len(file_jamo_v1_health_proto_rawDesc)))
	})
	return file_jamo_v1_health_proto_rawDescData
}

var file_jamo_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jamo_v1_health_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: jamo.v1.PingRequest
	(*PingResponse)(nil), // 1: jamo.v1.PingResponse
}
var file_jamo_v1_health_proto_depIdxs = []int32{
	0, // 0: jamo.v1.HealthService.Ping:input_type -> jamo.v1.PingRequest
	1, // 1: jamo.v1.HealthService.Ping:output_type -> jamo.v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jamo_v1_health_proto_init() }
func file_jamo_v1_health_proto_init() {
	if File_jamo_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jamo_v1_health_proto_rawDesc), len(file_jamo_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jamo_v1_health_proto_goTypes,
		DependencyIndexes: file_jamo_v1_health_proto_depIdxs,
		MessageInfos:      file_jamo_v1_health_proto_msgTypes,
	}.Build()
	File_jamo_v1_health_proto = out.File
	file_jamo_v1_health_proto_goTypes = nil
	file_jamo_v1_health_proto_depIdxs = nil
}
