// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jamo/v1/terminal.proto

package jamov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTerminalRequest) Reset() {
	*x = CreateTerminalRequest{}
	mi := &file_jamo_v1_terminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTerminalRequest) ProtoMessage() {}

func (x *CreateTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_terminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTerminalRequest.ProtoReflect.Descriptor instead.
func (*CreateTerminalRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_terminal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTerminalRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateTerminalRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CreateTerminalRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type CreateTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTerminalResponse) Reset() {
	*x = CreateTerminalResponse{}
	mi := &file_jamo_v1_terminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTerminalResponse) ProtoMessage() {}

func (x *CreateTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_terminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTerminalResponse.ProtoReflect.Descriptor instead.
func (*CreateTerminalResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_terminal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTerminalResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TerminalInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalInput_Data
	//	*TerminalInput_Resize
	Payload       isTerminalInput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalInput) Reset() {
	*x = TerminalInput{}
	mi := &file_jamo_v1_terminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInput) ProtoMessage() {}

func (x *TerminalInput) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_terminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInput.ProtoReflect.Descriptor instead.
func (*TerminalInput) Descriptor() ([]byte, []int) {
	return file_jamo_v1_terminal_proto_rawDescGZIP(), []int{2}
}

func (x *TerminalInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalInput) GetPayload() isTerminalInput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalInput) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TerminalInput_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TerminalInput) GetResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*TerminalInput_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isTerminalInput_Payload interface {
	isTerminalInput_Payload()
}

type TerminalInput_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type TerminalInput_Resize struct {
	Resize *TerminalResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*TerminalInput_Data) isTerminalInput_Payload() {}

func (*TerminalInput_Resize) isTerminalInput_Payload() {}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_jamo_v1_terminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_terminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_jamo_v1_terminal_proto_rawDescGZIP(), []int{3}
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOutput) Reset() {
	*x = TerminalOutput{}
	mi := &file_jamo_v1_terminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOutput) ProtoMessage() {}

func (x *TerminalOutput) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_terminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOutput.ProtoReflect.Descriptor instead.
func (*TerminalOutput) Descriptor() ([]byte, []int) {
	return file_jamo_v1_terminal_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminalOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jamo_v1_terminal_proto protoreflect.FileDescriptor

const file_jamo_v1_terminal_proto_rawDesc = "" +
	"\n" +
	"\x16jamo/v1/terminal.proto\x12\ajamo.v1\"b\n" +
	"\x15CreateTerminalRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"7\n" +
	"\x16CreateTerminalResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x82\x01\n" +
	"\rTerminalInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x121\n" +
	"\x06resize\x18\x03 \x01(\v2\x17.jamo.v1.TerminalResizeH\x00R\x06resizeB\t\n" +
	"\apayload\"8\n" +
	"\x0eTerminalResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"C\n" +
	"\x0eTerminalOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xab\x01\n" +
	"\x0fTerminalService\x12Q\n" +
	"\x0eCreateTerminal\x12\x1e.jamo.v1.CreateTerminalRequest\x1a\x1f.jamo.v1.CreateTerminalResponse\x12E\n" +
	"\x0eTerminalStream\x12\x16.jamo.v1.TerminalInput\x1a\x17.jamo.v1.TerminalOutput(\x010\x01B8Z6github.com/jamojamo/studio/engine/proto/jamo/v1;jamov1b\x06proto3"

var (
	file_jamo_v1_terminal_proto_rawDescOnce sync.Once
	file_jamo_v1_terminal_proto_rawDescData []byte
)

func file_jamo_v1_terminal_proto_rawDescGZIP() []byte {
	file_jamo_v1_terminal_proto_rawDescOnce.Do(func() {
		file_jamo_v1_terminal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jamo_v1_terminal_proto_rawDesc), len(file_jamo_v1_terminal_proto_rawDesc)))
	})
	return file_jamo_v1_terminal_proto_rawDescData
}

var file_jamo_v1_terminal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jamo_v1_terminal_proto_goTypes = []any{
	(*CreateTerminalRequest)(nil),  // 0: jamo.v1.CreateTerminalRequest
	(*CreateTerminalResponse)(nil), // 1: jamo.v1.CreateTerminalResponse
	(*TerminalInput)(nil),          // 2: jamo.v1.TerminalInput
	(*TerminalResize)(nil),         // 3: jamo.v1.TerminalResize
	(*TerminalOutput)(nil),         // 4: jamo.v1.TerminalOutput
}
var file_jamo_v1_terminal_proto_depIdxs = []int32{
	3, // 0: jamo.v1.TerminalInput.resize:type_name -> jamo.v1.TerminalResize
	0, // 1: jamo.v1.TerminalService.CreateTerminal:input_type -> jamo.v1.CreateTerminalRequest
	2, // 2: jamo.v1.TerminalService.TerminalStream:input_type -> jamo.v1.TerminalInput
	1, // 3: jamo.v1.TerminalService.CreateTerminal:output_type -> jamo.v1.CreateTerminalResponse
	4, // 4: jamo.v1.TerminalService.TerminalStream:output_type -> jamo.v1.TerminalOutput
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jamo_v1_terminal_proto_init() }
func file_jamo_v1_terminal_proto_init() {
	if File_jamo_v1_terminal_proto != nil {
		return
	}
	file_jamo_v1_terminal_proto_msgTypes[2].OneofWrappers = []any{
		(*TerminalInput_Data)(nil),
		(*TerminalInput_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jamo_v1_terminal_proto_rawDesc), len(file_jamo_v1_terminal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jamo_v1_terminal_proto_goTypes,
		DependencyIndexes: file_jamo_v1_terminal_proto_depIdxs,
		MessageInfos:      file_jamo_v1_terminal_proto_msgTypes,
	}.Build()
	File_jamo_v1_terminal_proto = out.File
	file_jamo_v1_terminal_proto_goTypes = nil
	file_jamo_v1_terminal_proto_depIdxs = nil
}
