// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: jamo/v1/workspace.proto

package jamov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenWorkspaceRequest) Reset() {
	*x = OpenWorkspaceRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenWorkspaceRequest) ProtoMessage() {}

func (x *OpenWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*OpenWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *OpenWorkspaceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenWorkspaceResponse) Reset() {
	*x = OpenWorkspaceResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenWorkspaceResponse) ProtoMessage() {}

func (x *OpenWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*OpenWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *OpenWorkspaceResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *OpenWorkspaceResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFileRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ReadFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *WriteFileRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WriteFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{5}
}

type ListDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirectoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListDirectoryRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type ListDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirectoryResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	OldPath       string                 `protobuf:"bytes,2,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,3,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileRequest) Reset() {
	*x = MoveFileRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileRequest) ProtoMessage() {}

func (x *MoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileRequest.ProtoReflect.Descriptor instead.
func (*MoveFileRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *MoveFileRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *MoveFileRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *MoveFileRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type MoveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileResponse) Reset() {
	*x = MoveFileResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileResponse) ProtoMessage() {}

func (x *MoveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileResponse.ProtoReflect.Descriptor instead.
func (*MoveFileResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{10}
}

type CreateDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryRequest) Reset() {
	*x = CreateDirectoryRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryRequest) ProtoMessage() {}

func (x *CreateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDirectoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateDirectoryRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type CreateDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryResponse) Reset() {
	*x = CreateDirectoryResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryResponse) ProtoMessage() {}

func (x *CreateDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{12}
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteFileRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_jamo_v1_workspace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jamo_v1_workspace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_jamo_v1_workspace_proto_rawDescGZIP(), []int{14}
}

var File_jamo_v1_workspace_proto protoreflect.FileDescriptor

const file_jamo_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x17jamo/v1/workspace.proto\x12\ajamo.v1\"*\n" +
	"\x14OpenWorkspaceRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"N\n" +
	"\x15OpenWorkspaceResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"Y\n" +
	"\x0fReadFileRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"t\n" +
	"\x10WriteFileRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\x13\n" +
	"\x11WriteFileResponse\"^\n" +
	"\x14ListDirectoryRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"E\n" +
	"\x15ListDirectoryResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.jamo.v1.FileEntryR\aentries\"J\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"j\n" +
	"\x0fMoveFileRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bold_path\x18\x02 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x03 \x01(\tR\anewPath\"\x12\n" +
	"\x10MoveFileResponse\"`\n" +
	"\x16CreateDirectoryRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"\x19\n" +
	"\x17CreateDirectoryResponse\"[\n" +
	"\x11DeleteFileRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\"\x14\n" +
	"\x12DeleteFileResponse2\x95\x04\n" +
	"\x10WorkspaceService\x12N\n" +
	"\rOpenWorkspace\x12\x1d.jamo.v1.OpenWorkspaceRequest\x1a\x1e.jamo.v1.OpenWorkspaceResponse\x12?\n" +
	"\bReadFile\x12\x18.jamo.v1.ReadFileRequest\x1a\x19.jamo.v1.ReadFileResponse\x12B\n" +
	"\tWriteFile\x12\x19.jamo.v1.WriteFileRequest\x1a\x1a.jamo.v1.WriteFileResponse\x12N\n" +
	"\rListDirectory\x12\x1d.jamo.v1.ListDirectoryRequest\x1a\x1e.jamo.v1.ListDirectoryResponse\x12?\n" +
	"\bMoveFile\x12\x18.jamo.v1.MoveFileRequest\x1a\x19.jamo.v1.MoveFileResponse\x12T\n" +
	"\x0fCreateDirectory\x12\x1f.jamo.v1.CreateDirectoryRequest\x1a .jamo.v1.CreateDirectoryResponse\x12E\n" +
	"\n" +
	"DeleteFile\x12\x1a.jamo.v1.DeleteFileRequest\x1a\x1b.jamo.v1.DeleteFileResponseB8Z6github.com/jamojamo/studio/engine/proto/jamo/v1;jamov1b\x06proto3"

var (
	file_jamo_v1_workspace_proto_rawDescOnce sync.Once
	file_jamo_v1_workspace_proto_rawDescData []byte
)

func file_jamo_v1_workspace_proto_rawDescGZIP() []byte {
	file_jamo_v1_workspace_proto_rawDescOnce.Do(func() {
		file_jamo_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jamo_v1_workspace_proto_rawDesc), len(file_jamo_v1_workspace_proto_rawDesc)))
	})
	return file_jamo_v1_workspace_proto_rawDescData
}

var file_jamo_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_jamo_v1_workspace_proto_goTypes = []any{
	(*OpenWorkspaceRequest)(nil),    // 0: jamo.v1.OpenWorkspaceRequest
	(*OpenWorkspaceResponse)(nil),   // 1: jamo.v1.OpenWorkspaceResponse
	(*ReadFileRequest)(nil),         // 2: jamo.v1.ReadFileRequest
	(*ReadFileResponse)(nil),        // 3: jamo.v1.ReadFileResponse
	(*WriteFileRequest)(nil),        // 4: jamo.v1.WriteFileRequest
	(*WriteFileResponse)(nil),       // 5: jamo.v1.WriteFileResponse
	(*ListDirectoryRequest)(nil),    // 6: jamo.v1.ListDirectoryRequest
	(*ListDirectoryResponse)(nil),   // 7: jamo.v1.ListDirectoryResponse
	(*FileEntry)(nil),               // 8: jamo.v1.FileEntry
	(*MoveFileRequest)(nil),         // 9: jamo.v1.MoveFileRequest
	(*MoveFileResponse)(nil),        // 10: jamo.v1.MoveFileResponse
	(*CreateDirectoryRequest)(nil),  // 11: jamo.v1.CreateDirectoryRequest
	(*CreateDirectoryResponse)(nil), // 12: jamo.v1.CreateDirectoryResponse
	(*DeleteFileRequest)(nil),       // 13: jamo.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),      // 14: jamo.v1.DeleteFileResponse
}
var file_jamo_v1_workspace_proto_depIdxs = []int32{
	8,  // 0: jamo.v1.ListDirectoryResponse.entries:type_name -> jamo.v1.FileEntry
	0,  // 1: jamo.v1.WorkspaceService.OpenWorkspace:input_type -> jamo.v1.OpenWorkspaceRequest
	2,  // 2: jamo.v1.WorkspaceService.ReadFile:input_type -> jamo.v1.ReadFileRequest
	4,  // 3: jamo.v1.WorkspaceService.WriteFile:input_type -> jamo.v1.WriteFileRequest
	6,  // 4: jamo.v1.WorkspaceService.ListDirectory:input_type -> jamo.v1.ListDirectoryRequest
	9,  // 5: jamo.v1.WorkspaceService.MoveFile:input_type -> jamo.v1.MoveFileRequest
	11, // 6: jamo.v1.WorkspaceService.CreateDirectory:input_type -> jamo.v1.CreateDirectoryRequest
	13, // 7: jamo.v1.WorkspaceService.DeleteFile:input_type -> jamo.v1.DeleteFileRequest
	1,  // 8: jamo.v1.WorkspaceService.OpenWorkspace:output_type -> jamo.v1.OpenWorkspaceResponse
	3,  // 9: jamo.v1.WorkspaceService.ReadFile:output_type -> jamo.v1.ReadFileResponse
	5,  // 10: jamo.v1.WorkspaceService.WriteFile:output_type -> jamo.v1.WriteFileResponse
	7,  // 11: jamo.v1.WorkspaceService.ListDirectory:output_type -> jamo.v1.ListDirectoryResponse
	10, // 12: jamo.v1.WorkspaceService.MoveFile:output_type -> jamo.v1.MoveFileResponse
	12, // 13: jamo.v1.WorkspaceService.CreateDirectory:output_type -> jamo.v1.CreateDirectoryResponse
	14, // 14: jamo.v1.WorkspaceService.DeleteFile:output_type -> jamo.v1.DeleteFileResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_jamo_v1_workspace_proto_init() }
func file_jamo_v1_workspace_proto_init() {
	if File_jamo_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jamo_v1_workspace_proto_rawDesc), len(file_jamo_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jamo_v1_workspace_proto_goTypes,
		DependencyIndexes: file_jamo_v1_workspace_proto_depIdxs,
		MessageInfos:      file_jamo_v1_workspace_proto_msgTypes,
	}.Build()
	File_jamo_v1_workspace_proto = out.File
	file_jamo_v1_workspace_proto_goTypes = nil
	file_jamo_v1_workspace_proto_depIdxs = nil
}
