// Package generatebus provides business logic for code generation (stub).
package generatebus

import (
	"context"

	"github.com/google/uuid"
	"github.com/jamojamo/studio/engine/foundation/logger"
)

// Patch represents a file modification.
type Patch struct {
	FilePath string
	Content  []byte
}

// Result represents the output of a generation run.
type Result struct {
	TaskID  string
	Patches []Patch
}

// Business manages code generation operations.
type Business struct {
	log *logger.Logger
}

// NewBusiness creates a new generate business instance.
func NewBusiness(log *logger.Logger) *Business {
	return &Business{
		log: log,
	}
}

// Generate runs a stub code generation, returning hardcoded fake patches.
func (b *Business) Generate(ctx context.Context, wsID, prompt string) (*Result, error) {
	b.log.Info(ctx, "generate started", "workspace", wsID, "prompt", prompt)

	taskID := uuid.New().String()

	// Stub: return a hardcoded patch.
	patches := []Patch{
		{
			FilePath: "generated.txt",
			Content:  []byte("// Generated by Jamo Studio\n// Prompt: " + prompt + "\n\nHello from Jamo!\n"),
		},
	}

	b.log.Info(ctx, "generate completed", "workspace", wsID, "task_id", taskID, "patches", len(patches))

	return &Result{
		TaskID:  taskID,
		Patches: patches,
	}, nil
}
